framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: snc_redis.default
        pools:
            topTags.cache:
                adapter: cache.adapter.redis
                #provider: snc_redis.cache
                #default_lifetime: 3600 #1 hour

        #pools:
        #    topTags.cache:
        #        default_lifetime: 3600 #1 hour
        #        adapter: cache.app
